[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "firescipy"
version = "0.0.4"
description = "FireSciPy: Fundamental algorithms from the field of fire science, for computations with Python."
readme = "README.md"
keywords = ["Fire Safety Engineering", "fire", "pyrolysis", "kinetics", "FDS"]
requires-python = ">=3.9"
license = { text = "CC-BY-4.0" }  # adjust if you use another license
license-files = ["LICEN[CS]E*"]
authors = [
  { name = "Tristan Hehnen", email = "you@example.com" },
  { name = "Lukas Arnold", email = "you@example.com" }
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering"
]
dependencies = [
    "numpy>=1.19.5",
    "scipy>=1.5.4",
    "pandas>=1.1.5",
    "matplotlib>=3.3.4",
    # Add other runtime dependencies here
]

[tool.hatch.build.targets.wheel]
packages = ["src/firescipy"]

[project.urls]
Repository = "https://github.com/FireDynamics/FireSciPy"
Documentation = "https://firedynamics.github.io/FireSciPy/"
Issues = "https://github.com/FireDynamics/FireSciPy/issues"
